"""
Django settings for Newpro project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES_DIRS = os.path.join(BASE_DIR2, 'templates')
STATIC_DIR = os.path.join(BASE_DIR2, 'static')
MEDIA_DIR = os.path.join(BASE_DIR2, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sef#u9!s@d*(cof3q%6*aiqbfch=dr-6e_=pnbf%nq8t)_e486'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'project',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Newpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Newpro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [STATIC_DIR]
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR

# Email & notification defaults (console backend for dev). Set these via env vars in production.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'pulipandi8158@gmail.com')

SITE_URL = os.environ.get('SITE_URL', 'https://w82sqcrg-8000.inc1.devtunnels.ms')   

# Optional Twilio configuration for SMS notifications (leave empty to disable SMS)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER', '')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'pulipandi8158@gmail.com'
EMAIL_HOST_PASSWORD = 'kovy ruva fjco aiug'


# Jazzmin Configuration for Enhanced Django Admin
JAZZMIN_SETTINGS = {
    "site_header": "Surabi Dental Clinic",
    "site_title": "Clinic Admin",
    "brand": "Surabi Dental",
    "welcome_sign": "Welcome to Surabi Dental Clinic Admin",
    "copyright": "Surabi Dental Clinic 2024-2025",
    
    # UI Configuration
    "search_model": ["project.Doctor", "project.Service", "project.Bookings"],
    "user_avatar": None,
    
    # Theme & Colors
    "theme": "default",
    "dark_mode_theme": "darkly",
    
    # Custom CSS/JS
    "custom_css": None,
    "custom_js": None,
    
    # Navbar settings
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "project.Doctor": "fas fa-user-md",
        "project.Service": "fas fa-stethoscope",
        "project.Bookings": "fas fa-calendar-check",
        "project.OTPVerification": "fas fa-shield-alt",
        "project.Feedback": "fas fa-comments",
    },
    
    # Sidebar configurations
    "show_search": True,
    "show_recent": True,
    "order_with_respect_to": ["auth", "project"],
    
    # Hide specific models
    "hide_models": [],
    
    # Hide specific apps
    "hide_apps": [],
    
    # Customizable admin title and branding
    "default_icon_children": "fas fa-chevron-right",
    "related_modal_theme": "dark",
    
    # Footer
    "show_footer": True,
    "footer_text": "Surabi Dental Clinic Management System",
    
    # Toasts
    "show_ui_builder": False,
    "ui_tweaks": {
        "navbar_small": False,
        "footer_small": False,
        "body_small": False,
        "brand_small": False,
        "brand_colour": False,
        "accent": "accent-primary",
        "navbar": "navbar-white",
        "sidebar": "sidebar-dark-primary",
        "sidebar_nav_small_text": False,
        "sidebar_disable_expand": False,
        "sidebar_nav_child_indent": False,
        "sidebar_nav_compact_style": False,
        "sidebar_nav_legacy_style": False,
        "sidebar_nav_flat_style": False,
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
}

