# Generated by assistant: add appointment_date field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
