# Generated by Django 5.2.9 on 2025-12-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
