# Generated by Django 5.2.10 on 2026-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat', help_text='Comma-separated days (Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=50),
        ),
    ]
